#!/bin/bash

# Setup script for Keycloak realm and client for MCP Joke Server

echo "=== Setting up Keycloak for MCP Joke Server ==="
echo ""
echo "Prerequisites:"
echo "1. Keycloak must be running (docker-compose up -d)"
echo "2. Default admin credentials: admin/admin"
echo ""
echo "Manual setup steps:"
echo ""
echo "1. Access Keycloak Admin Console:"
echo "   http://localhost:8080/admin"
echo ""
echo "2. Create a new realm:"
echo "   - Click on 'master' dropdown → 'Create Realm'"
echo "   - Realm name: mcp"
echo "   - Click 'Create'"
echo ""
echo "3. Create a client for the MCP server:"
echo "   - Go to Clients → Create client"
echo "   - Client type: OpenID Connect"
echo "   - Client ID: mcp-joke-server"
echo "   - Click 'Next'"
echo "   - Client authentication: ON"
echo "   - Authorization: ON"
echo "   - Click 'Next'"
echo "   - Valid redirect URIs: http://localhost:*"
echo "   - Click 'Save'"
echo ""
echo "4. Create a client for MCP Inspector:"
echo "   - Go to Clients → Create client"
echo "   - Client type: OpenID Connect"
echo "   - Client ID: mcp-inspector"
echo "   - Click 'Next'"
echo "   - Client authentication: OFF (public client)"
echo "   - Click 'Next'"
echo "   - Valid redirect URIs: http://localhost:6274/*"
echo "   - Web origins: http://localhost:6274"
echo "   - Click 'Save'"
echo ""
echo "5. Create a test user:"
echo "   - Go to Users → Add user"
echo "   - Username: testuser"
echo "   - Email: testuser@example.com"
echo "   - Click 'Create'"
echo "   - Go to Credentials tab"
echo "   - Set password: testpass"
echo "   - Temporary: OFF"
echo "   - Click 'Set Password'"
echo ""
echo "6. Create a scope for mom jokes:"
echo "   - Go to Client scopes → Create client scope"
echo "   - Name: tools:mom_jokes"
echo "   - Type: Optional"
echo "   - Click 'Save'"
echo ""
echo "7. Assign scope to mcp-joke-server client:"
echo "   - Go to Clients → mcp-joke-server → Client scopes"
echo "   - Add client scope → Select 'tools:mom_jokes'"
echo "   - Add as 'Optional'"
echo ""
echo "Environment variables for the server:"
echo "export KEYCLOAK_URL=http://localhost:8080"
echo "export KEYCLOAK_REALM=mcp"
echo "export RESOURCE_SERVER_URL=http://localhost:8000"
echo ""
echo "To test with a token:"
echo "1. Get an access token using the password grant (for testing only):"
echo "   curl -X POST http://localhost:8080/realms/mcp/protocol/openid-connect/token \\"
echo "     -H 'Content-Type: application/x-www-form-urlencoded' \\"
echo "     -d 'grant_type=password&client_id=mcp-inspector&username=testuser&password=testpass&scope=tools:mom_jokes'"
echo ""
echo "2. Use the token to call the protected tool:"
echo "   curl -X POST http://localhost:8000/mcp \\"
echo "     -H 'Authorization: Bearer <access_token>' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"get_mom_joke\",\"arguments\":{}}}'"